// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Countries
    {
        constructor (ID: int, Name: string, Nationality: string)
        {
    		this.id = ID;
    		this.name = Name;
    		this.nationality = Nationality;
        }
    
    	id : int;
    	name : string;
    	nationality : string;
    }
}
