// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Currencies
    {
        constructor (ID: int, Name: string, ISOCode: string)
        {
    		this.id = ID;
    		this.name = Name;
    		this.isocode = ISOCode;
        }
    
    	id : int;
    	name : string;
    	isocode : string;
    
    	settings : Settings[];
    }
}
