// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class DoctorsInfo
    {
        constructor (ID: int, OrdinationID: int, FirstName: string, LastName: string, Title: string, Archived: bool, OrdinationName: string)
        {
    		this.id = ID;
    		this.ordinationid = OrdinationID;
    		this.firstname = FirstName;
    		this.lastname = LastName;
    		this.title = Title;
    		this.archived = Archived;
    		this.ordinationname = OrdinationName;
        }
    
    	id : int;
    	ordinationid : int;
    	firstname : string;
    	lastname : string;
    	title : string;
    	archived : bool;
    	ordinationname : string;
    }
}
