// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class LaboratoriesInfo
    {
        constructor (ID: int, Name: string, Archived: bool, OrganizationID: int, OrganizationName: string)
        {
    		this.id = ID;
    		this.name = Name;
    		this.archived = Archived;
    		this.organizationid = OrganizationID;
    		this.organizationname = OrganizationName;
        }
    
    	id : int;
    	name : string;
    	archived : bool;
    	organizationid : int;
    	organizationname : string;
    }
}
