// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Locations
    {
        constructor (ID: int, OrganizationID: int, Name: string)
        {
    		this.id = ID;
    		this.organizationid = OrganizationID;
    		this.name = Name;
        }
    
    	id : int;
       	organizationid : int;
       	name : string;
       
    	organizations : Organizations[];
    	works : Works[];
    	laboratories : Laboratories[];
    	ordinations : Ordinations[];
    	users : Users[];
    }
}
