//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FuturaDentalEntities : DbContext
    {
        public FuturaDentalEntities()
            : base("name=FuturaDentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actions> Actions { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<Currencies> Currencies { get; set; }
        public DbSet<Doctors> Doctors { get; set; }
        public DbSet<Laboratories> Laboratories { get; set; }
        public DbSet<Languages> Languages { get; set; }
        public DbSet<Locations> Locations { get; set; }
        public DbSet<LocationTypes> LocationTypes { get; set; }
        public DbSet<Ordinations> Ordinations { get; set; }
        public DbSet<Organizations> Organizations { get; set; }
        public DbSet<PositionStates> PositionStates { get; set; }
        public DbSet<Resources> Resources { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Settings> Settings { get; set; }
        public DbSet<Statuses> Statuses { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Workers> Workers { get; set; }
        public DbSet<WorkGroups> WorkGroups { get; set; }
        public DbSet<WorkMarks> WorkMarks { get; set; }
        public DbSet<Works> Works { get; set; }
        public DbSet<WorksComments> WorksComments { get; set; }
        public DbSet<WorksDetails> WorksDetails { get; set; }
        public DbSet<WorksPositions> WorksPositions { get; set; }
        public DbSet<WorkTypes> WorkTypes { get; set; }
        public DbSet<DoctorsInfo> DoctorsInfo { get; set; }
        public DbSet<LaboratoriesInfo> LaboratoriesInfo { get; set; }
        public DbSet<OrdinationsInfo> OrdinationsInfo { get; set; }
        public DbSet<UsersInfo> UsersInfo { get; set; }
        public DbSet<WorksCommentsInfo> WorksCommentsInfo { get; set; }
        public DbSet<WorksInfo> WorksInfo { get; set; }
        public DbSet<WorksPositionsInfo> WorksPositionsInfo { get; set; }
        public DbSet<WorkTypesInfo> WorkTypesInfo { get; set; }
    }
}
