// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Ordinations
    {
        constructor (ID: int, OrganizationID: int, Name: string, Address: string, Telephone: string, Email: string, Archived: bool)
        {
    		this.id = ID;
    		this.organizationid = OrganizationID;
    		this.name = Name;
    		this.address = Address;
    		this.telephone = Telephone;
    		this.email = Email;
    		this.archived = Archived;
        }
    
    	id : int;
    	organizationid : int;
    	name : string;
    	address : string;
    	telephone : string;
    	email : string;
    	archived : bool;
    
    	doctors : Doctors[];
    	organizations : Organizations[];
    	works : Works[];
    	locations : Locations[];
    }
}
