// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Organizations
    {
        constructor (ID: int, Name: string)
        {
    		this.id = ID;
    		this.name = Name;
        }
    
    	id : int;
    	name : string;
    
    	laboratories : Laboratories[];
    	locations : Locations[];
    	ordinations : Ordinations[];
    	positionstates : PositionStates[];
    	settings : Settings[];
    	users : Users[];
    	worktypes : WorkTypes[];
    }
}
