// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Resources
    {
        constructor (ID: int, TableName: string, FieldName: string, LanguageID: int, ResourceValue: string)
        {
    		this.id = ID;
    		this.tablename = TableName;
    		this.fieldname = FieldName;
    		this.languageid = LanguageID;
    		this.resourcevalue = ResourceValue;
        }
    
    	id : int;
    	tablename : string;
    	fieldname : string;
    	languageid : int;
    	resourcevalue : string;
    
    	languages : Languages[];
    }
}
