// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Settings
    {
        constructor (ID: int, OrganizationID: Nullable<int>, CurrencyID: int, LanguageID: int)
        {
    		this.id = ID;
    		this.organizationid = OrganizationID;
    		this.currencyid = CurrencyID;
    		this.languageid = LanguageID;
        }
    
    	id : int;
    	organizationid : Nullable<int>;
    	currencyid : int;
    	languageid : int;
    
    	currencies : Currencies[];
    	languages : Languages[];
    	organizations : Organizations[];
    }
}
