// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class sysdiagrams
    {
        constructor (name: string, principal_id: int, diagram_id: int, version: Nullable<int>, definition: byte[])
        {
    		this.name = name;
    		this.principal_id = principal_id;
    		this.diagram_id = diagram_id;
    		this.version = version;
    		this.definition = definition;
        }
    
    	name : string;
    	principal_id : int;
    	diagram_id : int;
    	version : Nullable<int>;
    	definition : byte[];
    }
}
