// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class UsersInfo
    {
        constructor (ID: int, Username: string, Password: string, Email: string, FirstName: string, LastName: string, Archived: bool, OrganizationID: int, OrganizationName: string)
        {
    		this.id = ID;
    		this.username = Username;
    		this.password = Password;
    		this.email = Email;
    		this.firstname = FirstName;
    		this.lastname = LastName;
    		this.archived = Archived;
    		this.organizationid = OrganizationID;
    		this.organizationname = OrganizationName;
        }
    
    	id : int;
       	username : string;
       	password : string;
       	email : string;
       	firstname : string;
       	lastname : string;
       	archived : var;
       	organizationid : int;
       	organizationname : string;
       }
}
