// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorksCommentsInfo
    {
        constructor (ID: int, WorkID: int, Comment: string, UserID: int, InsertTime: System.DateTime, UserFirstName: string, UserLastName: string, UserEmail: string)
        {
    		this.id = ID;
    		this.workid = WorkID;
    		this.comment = Comment;
    		this.userid = UserID;
    		this.inserttime = InsertTime;
    		this.userfirstname = UserFirstName;
    		this.userlastname = UserLastName;
    		this.useremail = UserEmail;
        }
    
    	id : int;
    	workid : int;
    	comment : string;
    	userid : int;
    	inserttime : System.DateTime;
    	userfirstname : string;
    	userlastname : string;
    	useremail : string;
    }
}
