// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Workers
    {
        constructor (ID: int, FirstName: string, LastName: string, LaboratoryID: Nullable<int>, Archived: bool)
        {
    		this.id = ID;
    		this.firstname = FirstName;
    		this.lastname = LastName;
    		this.laboratoryid = LaboratoryID;
    		this.archived = Archived;
        }
    
    	id : int;
    	firstname : string;
    	lastname : string;
    	laboratoryid : Nullable<int>;
    	archived : bool;
    
    	laboratories : Laboratories[];
    }
}
