// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorksPositions
    {
        constructor (ID: int, WorkID: int, Position: int, StateID: int, WorkTypeID: Nullable<int>, BridgeID: Nullable<int>, BridgePosition: Nullable<int>, Comment: string, WorkMarkID: Nullable<int>)
        {
    		this.id = ID;
    		this.workid = WorkID;
    		this.position = Position;
    		this.stateid = StateID;
    		this.worktypeid = WorkTypeID;
    		this.bridgeid = BridgeID;
    		this.bridgeposition = BridgePosition;
    		this.comment = Comment;
    		this.workmarkid = WorkMarkID;
        }
    
    	id : int;
       	workid : int;
       	position : int;
       	stateid : int;
       	worktypeid : int?;
       	bridgeid : int?;
       	bridgeposition : int?;
       	comment : string;
       	workmarkid : int?;
       
    	positionstates : PositionStates[];
    	workmarks : WorkMarks[];
    	works : Works[];
    	worktypes : WorkTypes[];
    }
}
