// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorksComments
    {
        constructor (ID: int, WorkID: int, Comment: string, UserID: int, InsertTime: System.DateTime)
        {
    		this.id = ID;
    		this.workid = WorkID;
    		this.comment = Comment;
    		this.userid = UserID;
    		this.inserttime = InsertTime;
        }
    
    	id : int;
       	workid : int;
       	comment : string;
       	userid : int;
       	inserttime : var;
       
    	users : Users[];
    	works : Works[];
    }
}
