// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorksPositionsInfo
    {
        constructor (ID: int, WorkID: int, Position: int, WorkTypeID: Nullable<int>, BridgeID: Nullable<int>, BridgePosition: Nullable<int>, WorkTypeParentID: Nullable<int>, WorkTypeName: string, Comment: string, StateID: int, WorkMarkID: Nullable<int>, WorkMarkName: string, StateName: string)
        {
    		this.id = ID;
    		this.workid = WorkID;
    		this.position = Position;
    		this.worktypeid = WorkTypeID;
    		this.bridgeid = BridgeID;
    		this.bridgeposition = BridgePosition;
    		this.worktypeparentid = WorkTypeParentID;
    		this.worktypename = WorkTypeName;
    		this.comment = Comment;
    		this.stateid = StateID;
    		this.workmarkid = WorkMarkID;
    		this.workmarkname = WorkMarkName;
    		this.statename = StateName;
        }
    
    	id : int;
       	workid : int;
       	position : int;
       	worktypeid : int?;
       	bridgeid : int?;
       	bridgeposition : int?;
       	worktypeparentid : int?;
       	worktypename : string;
       	comment : string;
       	stateid : int;
       	workmarkid : int?;
       	workmarkname : string;
       	statename : string;
       }
}
