// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorksInfo
    {
        constructor (ID: int, LaboratoryID: Nullable<int>, OrdinationID: int, DoctorID: Nullable<int>, PatientName: string, PatientAddress: string, PatientPhone: string, Notes: string, Status: int, LocationID: int, UserID: int, InsertTime: System.DateTime, Priority: int, RequestedTestTime: Nullable<System.DateTime>, RequestedFinishTime: Nullable<System.DateTime>, LaboratoryName: string, OrdinationName: string, DoctorFirstName: string, DoctorLastName: string, DoctorTitle: string, LocationName: string, UserFirstName: string, UserLastName: string)
        {
    		this.id = ID;
    		this.laboratoryid = LaboratoryID;
    		this.ordinationid = OrdinationID;
    		this.doctorid = DoctorID;
    		this.patientname = PatientName;
    		this.patientaddress = PatientAddress;
    		this.patientphone = PatientPhone;
    		this.notes = Notes;
    		this.status = Status;
    		this.locationid = LocationID;
    		this.userid = UserID;
    		this.inserttime = InsertTime;
    		this.priority = Priority;
    		this.requestedtesttime = RequestedTestTime;
    		this.requestedfinishtime = RequestedFinishTime;
    		this.laboratoryname = LaboratoryName;
    		this.ordinationname = OrdinationName;
    		this.doctorfirstname = DoctorFirstName;
    		this.doctorlastname = DoctorLastName;
    		this.doctortitle = DoctorTitle;
    		this.locationname = LocationName;
    		this.userfirstname = UserFirstName;
    		this.userlastname = UserLastName;
        }
    
    	id : int;
    	laboratoryid : Nullable<int>;
    	ordinationid : int;
    	doctorid : Nullable<int>;
    	patientname : string;
    	patientaddress : string;
    	patientphone : string;
    	notes : string;
    	status : int;
    	locationid : int;
    	userid : int;
    	inserttime : System.DateTime;
    	priority : int;
    	requestedtesttime : Nullable<System.DateTime>;
    	requestedfinishtime : Nullable<System.DateTime>;
    	laboratoryname : string;
    	ordinationname : string;
    	doctorfirstname : string;
    	doctorlastname : string;
    	doctortitle : string;
    	locationname : string;
    	userfirstname : string;
    	userlastname : string;
    }
}
