// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class Works
    {
        constructor (ID: int, LaboratoryID: Nullable<int>, OrdinationID: int, DoctorID: Nullable<int>, PatientName: string, PatientAddress: string, PatientPhone: string, Notes: string, Status: int, LocationID: int, UserID: int, InsertTime: System.DateTime, Priority: int, RequestedTestTime: Nullable<System.DateTime>, RequestedFinishTime: Nullable<System.DateTime>)
        {
    		this.id = ID;
    		this.laboratoryid = LaboratoryID;
    		this.ordinationid = OrdinationID;
    		this.doctorid = DoctorID;
    		this.patientname = PatientName;
    		this.patientaddress = PatientAddress;
    		this.patientphone = PatientPhone;
    		this.notes = Notes;
    		this.status = Status;
    		this.locationid = LocationID;
    		this.userid = UserID;
    		this.inserttime = InsertTime;
    		this.priority = Priority;
    		this.requestedtesttime = RequestedTestTime;
    		this.requestedfinishtime = RequestedFinishTime;
        }
    
    	id : int;
       	laboratoryid : int?;
       	ordinationid : int;
       	doctorid : int?;
       	patientname : string;
       	patientaddress : string;
       	patientphone : string;
       	notes : string;
       	status : int;
       	locationid : int;
       	userid : int;
       	inserttime : var;
       	priority : int;
       	requestedtesttime : var?;
       	requestedfinishtime : var?;
       
    	doctors : Doctors[];
    	laboratories : Laboratories[];
    	locations : Locations[];
    	ordinations : Ordinations[];
    	users : Users[];
    	workscomments : WorksComments[];
    	worksdetails : WorksDetails[];
    	workspositions : WorksPositions[];
    }
}
