// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorkTypesInfo
    {
        constructor (ID: int, ParentID: Nullable<int>, Name: string, Archived: bool, OrganizationID: int, OrganizationName: string, ParentName: string)
        {
    		this.id = ID;
    		this.parentid = ParentID;
    		this.name = Name;
    		this.archived = Archived;
    		this.organizationid = OrganizationID;
    		this.organizationname = OrganizationName;
    		this.parentname = ParentName;
        }
    
    	id : int;
    	parentid : Nullable<int>;
    	name : string;
    	archived : bool;
    	organizationid : int;
    	organizationname : string;
    	parentname : string;
    }
}
