// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorkTypes
    {
        constructor (ID: int, ParentID: Nullable<int>, Name: string, OrganizationID: int, Archived: bool)
        {
    		this.id = ID;
    		this.parentid = ParentID;
    		this.name = Name;
    		this.organizationid = OrganizationID;
    		this.archived = Archived;
        }
    
    	id : int;
    	parentid : Nullable<int>;
    	name : string;
    	organizationid : int;
    	archived : bool;
    
    	organizations : Organizations[];
    	worksdetails : WorksDetails[];
    	workspositions : WorksPositions[];
    	worktypes1 : WorkTypes1[];
    	worktypes2 : WorkTypes2[];
    }
}
