// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

module Template
{
    export class WorkMarks
    {
        constructor (ID: int, Name: string, Archived: bool)
        {
    		this.id = ID;
    		this.name = Name;
    		this.archived = Archived;
        }
    
    	id : int;
       	name : string;
       	archived : var;
       
    	workspositions : WorksPositions[];
    }
}
